# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-07 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomtype', models.CharField(blank=True, choices=[('1 in 1', '1 in 1'), ('2 in 1', '2 in 1'), ('3 in 1', '3 in 1'), ('4 in 1', '4 in 1')], max_length=100, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
